CREATE TABLE SYS.EmployeeJob(
    JobId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    JobTitle VARCHAR2(50) NOT NULL,
    Employer VARCHAR2(50) NOT NULL,
    Description VARCHAR2(50) NOT NULL,
    EmploymentHistoryId NUMBER NOT NULL,
    PRIMARY KEY(JobId),
    FOREIGN KEY(EmploymentHistoryId) REFERENCES EmploymentHistory(EmploymentHistoryId) 
    ON DELETE CASCADE
);


INSERT INTO  EmployeeJob(JobTitle,Employer,Description,EmploymentHistoryId) values ('Tester', 'Infosys', 'Infosys is a company', 2);
INSERT INTO SYS.EmploymentHistory(EmploymentFrom,EmploymentTo) VALUES ('1-1-1019', '2-3-2019');



CREATE TABLE SYS.EmploymentHistory(
    EmploymentHistoryId NUMBER GENERATED BY DEFAULT AS IDENTITY,
    EmploymentFrom DATE NOT NULL,
    EmploymentTo DATE NOT NULL,
    PRIMARY KEY(EmploymentHistoryId)
);

DELETE FROM EMPLOYMENTHISTORY;
DELETE FROM EmployeeJob;

SELECT * FROM EMPLOYMENTHISTORY;
SELECT * FROM EmployeeJob;

COMMIT;

SELECT * FROM EmployeeJob JOIN EmploymentHistory ON EmployeeJob.EmploymentHistoryId = EmploymentHistory.EmploymentHistoryId WHERE EmployeeJob.Jobid=1;

UPDATE EmploymentHistory SET EmploymentFrom='26-12-1997', EmploymentTo='26-1-2019' WHERE EmploymentHistoryId = 1;


CREATE TABLE empInfo (
empno NUMBER(4) PRIMARY KEY,
empName VARCHAR2(20) NOT NULL,
hiredate DATE,
salary NUMBER(7,2),
jobDescription Clob,
byteCodes BLOB
);
 
Insert into empInfo(EMPNO,EMPNAME,JOBDESCRIPTION,byteCodes) values 
(1,'KING','SOFTWARE ENGR', '5657');
Insert into empInfo(EMPNO,EMPNAME,JOBDESCRIPTION,byteCodes) values 
(2,'SCOTT','MANAGER', '5960');
commit;







